apiVersion: dashboard.opendatahub.io/v1
kind: AcceleratorProfile
metadata:
  name: amd
  namespace: redhat-ods-applications
spec:
  displayName: AMD
  enabled: true
  # TODO(SG): What should the identifier be? instinct.ai/amd OR rocm.ai/amd
  identifier: habana.ai/gaudi
  tolerations: []
