apiVersion: v2
description: A Helm chart for RHODS (Red Hat OpenShift Data Science) deployment of AMD-related addons
keywords:
- rhods-operator-amd-addons
name: rhods-operator-amd-addons
version: 0.0.1
