global: 
  pattern: amdllm

  amdllm:
    namespace: amd-llm
    build_envs: [] # http_proxy/https_prxy can be set here 
    runtime_envs: []

    service_name: retriever
    service_port: 5004
    container_port: 7000
    route_path: /v1/retrieval
    docker_file_Path: comps/retrievers/src/Dockerfile
    working_dir: /home/user/comps/retrievers/src

    git_repo_uri: https://github.com/opea-project/GenAIComps.git
    image: image-registry.openshift-image-registry.svc:5000/opea/retriever:latest
    git_ref: 9e5e9be   # make sure to validate buildconfig & other change scope before updating

    secret:
      name: hf-token-secret
      key: huggingface
      env_var_name: HUGGINGFACEHUB_API_TOKEN

    tei_service:
      name: tei-embedding-service
      port: 5007
      env_var_name: TEI_EMBEDDING_ENDPOINT

    env:
      - name: HOME
        value: /tmp/temp-data
      - name: PYTHONPATH
        value: /home/user/.local/lib/python3.11/site-packages:/home/user
      - name: INDEX_NAME
        value: rag-redis
      - name: REDIS_URL
        value: redis://redis-vector-db.amd-llm.svc.cluster.local:6379
      - name: NLTK_DATA
        value: /tmp/temp-data/nltk_data

    volume:
      - name: temp-data
        path: /tmp/temp-data
