{{- range $key, $value := .Values.global.amdllm.deployments }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: {{ $value.service_name }}
  name: {{ $value.service_name }}
  namespace: {{ $.Values.global.amdllm.namespace }}
spec:
  ports:
    - name: "{{ $value.service_port }}"
      port: {{ $value.service_port }}
      targetPort: {{ $value.container_port }}
  selector:
    io.kompose.service: {{ $value.name }}
{{- end}}
