{{- range $key, $value := .Values.global.amdllm.deployments }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: {{ $value.name }}-claim0
  name: {{ $value.name }}-claim0
  namespace: {{ $.Values.global.amdllm.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.global.amdllm.pvc.size }}
{{- end}}
