apiVersion: v1
kind: ConfigMap
metadata:
  name: create-rhoai-istio-rootca-cert-secret
  namespace: {{ .Values.global.amdllm.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  create-rhoai-istio-rootca-cert-secret.sh: |
    #!/bin/bash

    TMP_KEY='tls.crt'

    SRC_SECRET=$(oc extract secret/knative-serving-cert -n istio-system --to=- --keys=${TMP_KEY})

    if [ -z "$SRC_SECRET" ]; then
      echo "Secret 'secret/knative-serving-cert' in namespace 'istio-system' is EMPTY. Will try again..."
    else
      TARGET_SECRET_NAME='tmp-secret'
      TMP_NS='amd-llm'
      echo "Deleting '$TARGET_SECRET_NAME' secret (if it exists)..."
      oc delete secret -n $TMP_NS $TARGET_SECRET_NAME --ignore-not-found=true

      echo "Creating '$TARGET_SECRET_NAME' secret (using knative-serving-cert)..."
      oc create secret generic -n $TMP_NS $TARGET_SECRET_NAME --from-literal=${TMP_KEY}="$SRC_SECRET"
    fi
