apiVersion: v1
kind: ConfigMap
metadata:
  name: create-rhoai-istio-rootca-cert-secret
  namespace: {{ .Values.global.amdllm.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  create-rhoai-istio-rootca-cert-secret.sh: |
    #!/bin/bash

    TMP_KEY='tls.crt'
    SRC_SECRET=$(oc extract secret/knative-serving-cert -n istio-system --to=- --keys=${TMP_KEY})

    if [ -z "$SRC_SECRET" ]; then
      echo "Secret 'secret/knative-serving-cert' in namespace 'istio-system' is EMPTY. Will try again..."
      exit 1
    else
      TARGET_SECRET_NAME='unused-rhoai-ca-bundle'
      SECRET_EXISTS=$(oc get secret --ignore-not-found $TARGET_SECRET_NAME -n {{ .Values.global.amdllm.namespace }})

      if [[ -z "${SECRET_EXISTS}" ]]; then
        echo "Creating '$TARGET_SECRET_NAME' secret (using knative-serving-cert)..."
        oc create secret generic -n {{ .Values.global.amdllm.namespace }} $TARGET_SECRET_NAME --from-literal=${TMP_KEY}="$SRC_SECRET"
      else
        echo "Secret '$TARGET_SECRET_NAME' already exists!!!"
      fi
    fi
