apiVersion: v1
kind: ConfigMap
metadata:
  name: create-rhoai-istio-rootca-cert-secret
  namespace: {{ .Values.global.amdllm.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  create-rhoai-istio-rootca-cert-secret.sh: |
    #!/bin/bash

    TMP_SECRET=$(oc extract secret/knative-serving-cert -n istio-system --to=- --keys=tls.crt)

    if [ -z "$TMP_SECRET" ]; then
      echo "Secret 'secret/knative-serving-cert' in namespace 'istio-system' is EMPTY. Will try again..."
    else
      oc create secret generic -n {{ .Values.global.amdllm.namespace }} deleted-me-rhoai-ca-bundle --from-literal=tls.crt="$TMP_SECRET"
    fi
