apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.rhoai_model.ocp.secret_name }}
  namespace: {{ .Values.global.amdllm.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secret_store.name }}
    kind: {{ .Values.secret_store.kind }}
  target:
    name: {{ .Values.secret.rhoai_model.ocp.secret_name }}
    template:
      type: Opaque
  data:
    - secretKey: {{ .Values.secret.rhoai_model.ocp.key }}
      remoteRef:
        key: {{ .Values.secret.rhoai_model.vault.path }}
        property: {{ .Values.secret.rhoai_model.vault.key }}
